import streamlit as st
import os
import google.generativeai as genai
from langchain_community.utilities import SQLDatabase
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_community.agent_toolkits import create_sql_agent
from fpdf import FPDF
import io
from langchain_community.vectorstores import Chroma
from langchain_google_genai import GoogleGenerativeAIEmbeddings

# PDF data ko process karne ke liye embeddings
embeddings = GoogleGenerativeAIEmbeddings(model="models/embedding-001")

# 'data/pdfs' folder mein rakhi files ko read karne ke liye vector store
# Note: Iske liye aapko 'data' folder banana hoga
vector_db = Chroma(persist_directory="./chroma_db", embedding_function=embeddings)

def ask_hybrid_analyst(question):
    # Pehle SQL se data nikalo
    sql_response = ask_data_analyst(question)
    
    # Phir PDFs mein se relevant context dhoondho
    pdf_context = vector_db.similarity_search(question, k=2)
    
    # Dono ko combine karke final jawab do
    return f"{sql_response}\n\n**Additional Context from PDF Reports:**\n{pdf_context[0].page_content}"

# 1. Configuration & Key Setup
gemini_key = st.secrets["GEMINI_API_KEY"]
genai.configure(api_key=gemini_key)

# Database Connection
MYSQL_URL = "sqlite:///historical_trends.db"
db = SQLDatabase.from_uri(MYSQL_URL)

# 2. Multi-Agent LLM Setup
# Gemini 2.0 Flash is fast and great for tool-use
llm = ChatGoogleGenerativeAI(model="gemini-2.0-flash", temperature=0)

# 3. Create the SQL AI Agent (The "Data Engineer" Agent)
agent_executor = create_sql_agent(
    llm=llm, 
    db=db, 
    agent_type="zero-shot-react-description", 
    verbose=True
)

# 4. Executive PDF Generator Tool
def generate_pdf_report(analysis_text):
    """Business stakeholders ke liye PDF report generate karta hai"""
    pdf = FPDF()
    pdf.add_page()
    
    # Header
    pdf.set_font("Arial", 'B', 16)
    pdf.cell(200, 10, txt="UPSC DATA ANALYST - EXECUTIVE BRIEF", ln=True, align='C')
    pdf.ln(10)
    
    # Body
    pdf.set_font("Arial", size=12)
    # Cleaning text for PDF compatibility
    clean_text = analysis_text.encode('latin-1', 'replace').decode('latin-1')
    pdf.multi_cell(0, 10, txt=clean_text)
    
    # Footer-style note
    pdf.ln(20)
    pdf.set_font("Arial", 'I', 8)
    pdf.cell(0, 10, txt="Generated by AI Data Analyst Team", align='R')
    
    return pdf.output(dest='S').encode('latin-1')

# 5. The Multi-Agent Orchestrator
def ask_data_analyst(question):
    try:
        # Step A: Data Engineer Agent fetches the data
        raw_data = agent_executor.invoke({"input": question})
        fetched_info = raw_data['output']
        
        # Step B: Executive Analyst Agent creates the brief
        # Hum LLM ko dubara call kar rahe hain ek 'Executive Summary' likhne ke liye
        summary_prompt = f"""
        As a Senior UPSC Consultant, analyze this data: {fetched_info}
        Provide an 'Executive Brief' including:
        1. Key Findings (Bullet points)
        2. Proactive Insights (For aspirants)
        3. Potential Anomalies (If any)
        Strictly use professional language.
        """
        executive_brief = llm.invoke(summary_prompt).content
        
        # Dono ko combine karke return karte hain
        full_response = f"{fetched_info}\n\n---\n### 📊 Executive Brief\n{executive_brief}"
        return full_response
        
    except Exception as e:
        if "429" in str(e):
            return "❌ Quota Exhausted! Please wait 1 minute. Free API limit reached."
        return f"❌ Error: {e}"
